# Default values for serverless
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
serverless:
  image:
    repository: jenkinsxio/jenkins-maven
    tag: 0.1.92
  imagePullPolicy: Always
  terminationGracePeriodSeconds: 30
  resources:
    limits:
     cpu: 400m
     memory: 1024Mi
    requests:
     cpu: 200m
     memory: 512Mi
